import { takeCharsUntil } from '../util.js'
import yaml from 'js-yaml'
import {
  TimelineItem,
  type TimelineItemOptions,
  type TimelineParsable,
} from './TimelineItem.js'
import { outerface } from '@johngw/outerface'

/**
 * The values that can be generated by the {@link TimelineItemDefault} item.
 */
export type TimelineItemDefaultValue = any

/**
 * Attempts to parse anything but a dash with `js-yaml`.
 */
@outerface<TimelineParsable<TimelineItemDefault>>()
export class TimelineItemDefault extends TimelineItem<TimelineItemDefaultValue> {
  #value: TimelineItemDefaultValue

  constructor(timeline: string, options: TimelineItemOptions) {
    super(timeline, options)
    this.#value = yaml.load(timeline) as TimelineItemDefaultValue
  }

  get() {
    return this.#value
  }

  static parse(timeline: string, options: TimelineItemOptions) {
    const unparsed = takeCharsUntil(timeline, '-')
    return unparsed.length
      ? ([
          new TimelineItemDefault(unparsed, options),
          timeline.slice(unparsed.length),
        ] as const)
      : undefined
  }
}
